/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.0.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPlainTextEdit>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *label;
    QPlainTextEdit *cuadro;
    QPlainTextEdit *cuadro_2;
    QPlainTextEdit *cuadro_3;
    QPlainTextEdit *cuadro_4;
    QPlainTextEdit *cuadro_5;
    QPlainTextEdit *cuadro_6;
    QPlainTextEdit *cuadro_7;
    QPlainTextEdit *cuadro_8;
    QPlainTextEdit *cuadro_9;
    QPlainTextEdit *cuadro_10;
    QPlainTextEdit *cuadro_11;
    QPlainTextEdit *cuadro_12;
    QPlainTextEdit *cuadro_13;
    QPlainTextEdit *cuadro_14;
    QPlainTextEdit *cuadro_15;
    QPlainTextEdit *cuadro_16;
    QPlainTextEdit *cuadro_17;
    QPlainTextEdit *cuadro_18;
    QPlainTextEdit *cuadro_19;
    QPlainTextEdit *cuadro_20;
    QPlainTextEdit *cuadro_21;
    QPlainTextEdit *cuadro_22;
    QPlainTextEdit *cuadro_23;
    QPlainTextEdit *cuadro_24;
    QPlainTextEdit *cuadro_25;
    QPlainTextEdit *cuadro_26;
    QPlainTextEdit *cuadro_27;
    QPlainTextEdit *cuadro_28;
    QPlainTextEdit *cuadro_29;
    QPlainTextEdit *cuadro_30;
    QPlainTextEdit *cuadro_31;
    QPlainTextEdit *cuadro_32;
    QPlainTextEdit *cuadro_33;
    QPlainTextEdit *cuadro_34;
    QPlainTextEdit *cuadro_35;
    QPlainTextEdit *cuadro_36;
    QPlainTextEdit *cuadro_37;
    QPlainTextEdit *cuadro_38;
    QPlainTextEdit *cuadro_39;
    QPlainTextEdit *cuadro_40;
    QPlainTextEdit *cuadro_41;
    QPlainTextEdit *cuadro_42;
    QPlainTextEdit *cuadro_43;
    QPlainTextEdit *cuadro_44;
    QPlainTextEdit *cuadro_45;
    QPlainTextEdit *cuadro_46;
    QPlainTextEdit *cuadro_47;
    QPlainTextEdit *cuadro_48;
    QPlainTextEdit *cuadro_49;
    QPlainTextEdit *cuadro_50;
    QPlainTextEdit *cuadro_51;
    QPlainTextEdit *cuadro_52;
    QPlainTextEdit *cuadro_53;
    QPlainTextEdit *cuadro_54;
    QPlainTextEdit *cuadro_55;
    QPlainTextEdit *cuadro_56;
    QPlainTextEdit *cuadro_57;
    QPlainTextEdit *cuadro_58;
    QPlainTextEdit *cuadro_59;
    QPlainTextEdit *cuadro_60;
    QPlainTextEdit *cuadro_61;
    QPlainTextEdit *cuadro_62;
    QPlainTextEdit *cuadro_63;
    QPlainTextEdit *cuadro_64;
    QPlainTextEdit *cuadro_65;
    QPlainTextEdit *cuadro_66;
    QPlainTextEdit *cuadro_67;
    QPlainTextEdit *cuadro_68;
    QPlainTextEdit *cuadro_69;
    QPlainTextEdit *cuadro_70;
    QPlainTextEdit *cuadro_71;
    QPlainTextEdit *cuadro_72;
    QPlainTextEdit *cuadro_73;
    QPlainTextEdit *cuadro_74;
    QPlainTextEdit *cuadro_75;
    QPlainTextEdit *cuadro_76;
    QPlainTextEdit *cuadro_77;
    QPlainTextEdit *cuadro_78;
    QPlainTextEdit *cuadro_79;
    QPlainTextEdit *cuadro_80;
    QPlainTextEdit *cuadro_81;
    QMenuBar *menuBar;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(400, 412);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(30, 0, 46, 13));
        cuadro = new QPlainTextEdit(centralWidget);
        cuadro->setObjectName(QStringLiteral("cuadro"));
        cuadro->setGeometry(QRect(30, 30, 31, 31));
        cuadro->setAcceptDrops(false);
        cuadro->setAutoFillBackground(false);
        cuadro->setMidLineWidth(1);
        cuadro->setOverwriteMode(true);
        cuadro->setMaximumBlockCount(1);
        cuadro->setBackgroundVisible(false);
        cuadro_2 = new QPlainTextEdit(centralWidget);
        cuadro_2->setObjectName(QStringLiteral("cuadro_2"));
        cuadro_2->setGeometry(QRect(60, 30, 31, 31));
        cuadro_2->setAcceptDrops(false);
        cuadro_2->setAutoFillBackground(false);
        cuadro_2->setOverwriteMode(true);
        cuadro_2->setMaximumBlockCount(1);
        cuadro_3 = new QPlainTextEdit(centralWidget);
        cuadro_3->setObjectName(QStringLiteral("cuadro_3"));
        cuadro_3->setGeometry(QRect(90, 30, 31, 31));
        cuadro_3->setAcceptDrops(false);
        cuadro_3->setAutoFillBackground(false);
        cuadro_3->setOverwriteMode(true);
        cuadro_3->setMaximumBlockCount(1);
        cuadro_4 = new QPlainTextEdit(centralWidget);
        cuadro_4->setObjectName(QStringLiteral("cuadro_4"));
        cuadro_4->setGeometry(QRect(120, 30, 31, 31));
        cuadro_4->setAcceptDrops(false);
        cuadro_4->setAutoFillBackground(false);
        cuadro_4->setOverwriteMode(true);
        cuadro_4->setMaximumBlockCount(1);
        cuadro_5 = new QPlainTextEdit(centralWidget);
        cuadro_5->setObjectName(QStringLiteral("cuadro_5"));
        cuadro_5->setGeometry(QRect(150, 30, 31, 31));
        cuadro_5->setAcceptDrops(false);
        cuadro_5->setAutoFillBackground(false);
        cuadro_5->setOverwriteMode(true);
        cuadro_5->setMaximumBlockCount(1);
        cuadro_6 = new QPlainTextEdit(centralWidget);
        cuadro_6->setObjectName(QStringLiteral("cuadro_6"));
        cuadro_6->setGeometry(QRect(180, 30, 31, 31));
        cuadro_6->setAcceptDrops(false);
        cuadro_6->setAutoFillBackground(false);
        cuadro_6->setOverwriteMode(true);
        cuadro_6->setMaximumBlockCount(1);
        cuadro_7 = new QPlainTextEdit(centralWidget);
        cuadro_7->setObjectName(QStringLiteral("cuadro_7"));
        cuadro_7->setGeometry(QRect(210, 30, 31, 31));
        cuadro_7->setAcceptDrops(false);
        cuadro_7->setAutoFillBackground(false);
        cuadro_7->setOverwriteMode(true);
        cuadro_7->setMaximumBlockCount(1);
        cuadro_8 = new QPlainTextEdit(centralWidget);
        cuadro_8->setObjectName(QStringLiteral("cuadro_8"));
        cuadro_8->setGeometry(QRect(240, 30, 31, 31));
        cuadro_8->setAcceptDrops(false);
        cuadro_8->setAutoFillBackground(false);
        cuadro_8->setOverwriteMode(true);
        cuadro_8->setMaximumBlockCount(1);
        cuadro_9 = new QPlainTextEdit(centralWidget);
        cuadro_9->setObjectName(QStringLiteral("cuadro_9"));
        cuadro_9->setGeometry(QRect(270, 30, 31, 31));
        cuadro_9->setAcceptDrops(false);
        cuadro_9->setAutoFillBackground(false);
        cuadro_9->setOverwriteMode(true);
        cuadro_9->setMaximumBlockCount(1);
        cuadro_10 = new QPlainTextEdit(centralWidget);
        cuadro_10->setObjectName(QStringLiteral("cuadro_10"));
        cuadro_10->setGeometry(QRect(30, 60, 31, 31));
        cuadro_10->setAcceptDrops(false);
        cuadro_10->setAutoFillBackground(false);
        cuadro_10->setOverwriteMode(true);
        cuadro_10->setMaximumBlockCount(1);
        cuadro_11 = new QPlainTextEdit(centralWidget);
        cuadro_11->setObjectName(QStringLiteral("cuadro_11"));
        cuadro_11->setGeometry(QRect(60, 60, 31, 31));
        cuadro_11->setAcceptDrops(false);
        cuadro_11->setAutoFillBackground(false);
        cuadro_11->setOverwriteMode(true);
        cuadro_11->setMaximumBlockCount(1);
        cuadro_12 = new QPlainTextEdit(centralWidget);
        cuadro_12->setObjectName(QStringLiteral("cuadro_12"));
        cuadro_12->setGeometry(QRect(90, 60, 31, 31));
        cuadro_12->setAcceptDrops(false);
        cuadro_12->setAutoFillBackground(false);
        cuadro_12->setOverwriteMode(true);
        cuadro_12->setMaximumBlockCount(1);
        cuadro_13 = new QPlainTextEdit(centralWidget);
        cuadro_13->setObjectName(QStringLiteral("cuadro_13"));
        cuadro_13->setGeometry(QRect(120, 60, 31, 31));
        cuadro_13->setAcceptDrops(false);
        cuadro_13->setAutoFillBackground(false);
        cuadro_13->setOverwriteMode(true);
        cuadro_13->setMaximumBlockCount(1);
        cuadro_14 = new QPlainTextEdit(centralWidget);
        cuadro_14->setObjectName(QStringLiteral("cuadro_14"));
        cuadro_14->setGeometry(QRect(150, 60, 31, 31));
        cuadro_14->setAcceptDrops(false);
        cuadro_14->setAutoFillBackground(false);
        cuadro_14->setOverwriteMode(true);
        cuadro_14->setMaximumBlockCount(1);
        cuadro_15 = new QPlainTextEdit(centralWidget);
        cuadro_15->setObjectName(QStringLiteral("cuadro_15"));
        cuadro_15->setGeometry(QRect(180, 60, 31, 31));
        cuadro_15->setAcceptDrops(false);
        cuadro_15->setAutoFillBackground(false);
        cuadro_15->setOverwriteMode(true);
        cuadro_15->setMaximumBlockCount(1);
        cuadro_16 = new QPlainTextEdit(centralWidget);
        cuadro_16->setObjectName(QStringLiteral("cuadro_16"));
        cuadro_16->setGeometry(QRect(210, 60, 31, 31));
        cuadro_16->setAcceptDrops(false);
        cuadro_16->setAutoFillBackground(false);
        cuadro_16->setOverwriteMode(true);
        cuadro_16->setMaximumBlockCount(1);
        cuadro_17 = new QPlainTextEdit(centralWidget);
        cuadro_17->setObjectName(QStringLiteral("cuadro_17"));
        cuadro_17->setGeometry(QRect(240, 60, 31, 31));
        cuadro_17->setAcceptDrops(false);
        cuadro_17->setAutoFillBackground(false);
        cuadro_17->setOverwriteMode(true);
        cuadro_17->setMaximumBlockCount(1);
        cuadro_18 = new QPlainTextEdit(centralWidget);
        cuadro_18->setObjectName(QStringLiteral("cuadro_18"));
        cuadro_18->setGeometry(QRect(270, 60, 31, 31));
        cuadro_18->setAcceptDrops(false);
        cuadro_18->setAutoFillBackground(false);
        cuadro_18->setOverwriteMode(true);
        cuadro_18->setMaximumBlockCount(1);
        cuadro_19 = new QPlainTextEdit(centralWidget);
        cuadro_19->setObjectName(QStringLiteral("cuadro_19"));
        cuadro_19->setGeometry(QRect(30, 90, 31, 31));
        cuadro_19->setAcceptDrops(false);
        cuadro_19->setAutoFillBackground(false);
        cuadro_19->setOverwriteMode(true);
        cuadro_19->setMaximumBlockCount(1);
        cuadro_20 = new QPlainTextEdit(centralWidget);
        cuadro_20->setObjectName(QStringLiteral("cuadro_20"));
        cuadro_20->setGeometry(QRect(60, 90, 31, 31));
        cuadro_20->setAcceptDrops(false);
        cuadro_20->setAutoFillBackground(false);
        cuadro_20->setOverwriteMode(true);
        cuadro_20->setMaximumBlockCount(1);
        cuadro_21 = new QPlainTextEdit(centralWidget);
        cuadro_21->setObjectName(QStringLiteral("cuadro_21"));
        cuadro_21->setGeometry(QRect(90, 90, 31, 31));
        cuadro_21->setAcceptDrops(false);
        cuadro_21->setAutoFillBackground(false);
        cuadro_21->setOverwriteMode(true);
        cuadro_21->setMaximumBlockCount(1);
        cuadro_22 = new QPlainTextEdit(centralWidget);
        cuadro_22->setObjectName(QStringLiteral("cuadro_22"));
        cuadro_22->setGeometry(QRect(120, 90, 31, 31));
        cuadro_22->setAcceptDrops(false);
        cuadro_22->setAutoFillBackground(false);
        cuadro_22->setOverwriteMode(true);
        cuadro_22->setMaximumBlockCount(1);
        cuadro_23 = new QPlainTextEdit(centralWidget);
        cuadro_23->setObjectName(QStringLiteral("cuadro_23"));
        cuadro_23->setGeometry(QRect(150, 90, 31, 31));
        cuadro_23->setAcceptDrops(false);
        cuadro_23->setAutoFillBackground(false);
        cuadro_23->setOverwriteMode(true);
        cuadro_23->setMaximumBlockCount(1);
        cuadro_24 = new QPlainTextEdit(centralWidget);
        cuadro_24->setObjectName(QStringLiteral("cuadro_24"));
        cuadro_24->setGeometry(QRect(180, 90, 31, 31));
        cuadro_24->setAcceptDrops(false);
        cuadro_24->setAutoFillBackground(false);
        cuadro_24->setOverwriteMode(true);
        cuadro_24->setMaximumBlockCount(1);
        cuadro_25 = new QPlainTextEdit(centralWidget);
        cuadro_25->setObjectName(QStringLiteral("cuadro_25"));
        cuadro_25->setGeometry(QRect(210, 90, 31, 31));
        cuadro_25->setAcceptDrops(false);
        cuadro_25->setAutoFillBackground(false);
        cuadro_25->setOverwriteMode(true);
        cuadro_25->setMaximumBlockCount(1);
        cuadro_26 = new QPlainTextEdit(centralWidget);
        cuadro_26->setObjectName(QStringLiteral("cuadro_26"));
        cuadro_26->setGeometry(QRect(240, 90, 31, 31));
        cuadro_26->setAcceptDrops(false);
        cuadro_26->setAutoFillBackground(false);
        cuadro_26->setOverwriteMode(true);
        cuadro_26->setMaximumBlockCount(1);
        cuadro_27 = new QPlainTextEdit(centralWidget);
        cuadro_27->setObjectName(QStringLiteral("cuadro_27"));
        cuadro_27->setGeometry(QRect(270, 90, 31, 31));
        cuadro_27->setAcceptDrops(false);
        cuadro_27->setAutoFillBackground(false);
        cuadro_27->setOverwriteMode(true);
        cuadro_27->setMaximumBlockCount(1);
        cuadro_28 = new QPlainTextEdit(centralWidget);
        cuadro_28->setObjectName(QStringLiteral("cuadro_28"));
        cuadro_28->setGeometry(QRect(210, 150, 31, 31));
        cuadro_28->setAcceptDrops(false);
        cuadro_28->setAutoFillBackground(false);
        cuadro_28->setOverwriteMode(true);
        cuadro_28->setMaximumBlockCount(1);
        cuadro_29 = new QPlainTextEdit(centralWidget);
        cuadro_29->setObjectName(QStringLiteral("cuadro_29"));
        cuadro_29->setGeometry(QRect(90, 180, 31, 31));
        cuadro_29->setAcceptDrops(false);
        cuadro_29->setAutoFillBackground(false);
        cuadro_29->setOverwriteMode(true);
        cuadro_29->setMaximumBlockCount(1);
        cuadro_30 = new QPlainTextEdit(centralWidget);
        cuadro_30->setObjectName(QStringLiteral("cuadro_30"));
        cuadro_30->setGeometry(QRect(270, 180, 31, 31));
        cuadro_30->setAcceptDrops(false);
        cuadro_30->setAutoFillBackground(false);
        cuadro_30->setOverwriteMode(true);
        cuadro_30->setMaximumBlockCount(1);
        cuadro_31 = new QPlainTextEdit(centralWidget);
        cuadro_31->setObjectName(QStringLiteral("cuadro_31"));
        cuadro_31->setGeometry(QRect(150, 180, 31, 31));
        cuadro_31->setAcceptDrops(false);
        cuadro_31->setAutoFillBackground(false);
        cuadro_31->setOverwriteMode(true);
        cuadro_31->setMaximumBlockCount(1);
        cuadro_32 = new QPlainTextEdit(centralWidget);
        cuadro_32->setObjectName(QStringLiteral("cuadro_32"));
        cuadro_32->setGeometry(QRect(60, 180, 31, 31));
        cuadro_32->setAcceptDrops(false);
        cuadro_32->setAutoFillBackground(false);
        cuadro_32->setOverwriteMode(true);
        cuadro_32->setMaximumBlockCount(1);
        cuadro_33 = new QPlainTextEdit(centralWidget);
        cuadro_33->setObjectName(QStringLiteral("cuadro_33"));
        cuadro_33->setGeometry(QRect(180, 180, 31, 31));
        cuadro_33->setAcceptDrops(false);
        cuadro_33->setAutoFillBackground(false);
        cuadro_33->setOverwriteMode(true);
        cuadro_33->setMaximumBlockCount(1);
        cuadro_34 = new QPlainTextEdit(centralWidget);
        cuadro_34->setObjectName(QStringLiteral("cuadro_34"));
        cuadro_34->setGeometry(QRect(120, 150, 31, 31));
        cuadro_34->setAcceptDrops(false);
        cuadro_34->setAutoFillBackground(false);
        cuadro_34->setOverwriteMode(true);
        cuadro_34->setMaximumBlockCount(1);
        cuadro_35 = new QPlainTextEdit(centralWidget);
        cuadro_35->setObjectName(QStringLiteral("cuadro_35"));
        cuadro_35->setGeometry(QRect(210, 120, 31, 31));
        cuadro_35->setAcceptDrops(false);
        cuadro_35->setAutoFillBackground(false);
        cuadro_35->setOverwriteMode(true);
        cuadro_35->setMaximumBlockCount(1);
        cuadro_36 = new QPlainTextEdit(centralWidget);
        cuadro_36->setObjectName(QStringLiteral("cuadro_36"));
        cuadro_36->setGeometry(QRect(30, 180, 31, 31));
        cuadro_36->setAcceptDrops(false);
        cuadro_36->setAutoFillBackground(false);
        cuadro_36->setOverwriteMode(true);
        cuadro_36->setMaximumBlockCount(1);
        cuadro_37 = new QPlainTextEdit(centralWidget);
        cuadro_37->setObjectName(QStringLiteral("cuadro_37"));
        cuadro_37->setGeometry(QRect(150, 120, 31, 31));
        cuadro_37->setAcceptDrops(false);
        cuadro_37->setAutoFillBackground(false);
        cuadro_37->setOverwriteMode(true);
        cuadro_37->setMaximumBlockCount(1);
        cuadro_38 = new QPlainTextEdit(centralWidget);
        cuadro_38->setObjectName(QStringLiteral("cuadro_38"));
        cuadro_38->setGeometry(QRect(180, 150, 31, 31));
        cuadro_38->setAcceptDrops(false);
        cuadro_38->setAutoFillBackground(false);
        cuadro_38->setOverwriteMode(true);
        cuadro_38->setMaximumBlockCount(1);
        cuadro_39 = new QPlainTextEdit(centralWidget);
        cuadro_39->setObjectName(QStringLiteral("cuadro_39"));
        cuadro_39->setGeometry(QRect(30, 150, 31, 31));
        cuadro_39->setAcceptDrops(false);
        cuadro_39->setAutoFillBackground(false);
        cuadro_39->setOverwriteMode(true);
        cuadro_39->setMaximumBlockCount(1);
        cuadro_40 = new QPlainTextEdit(centralWidget);
        cuadro_40->setObjectName(QStringLiteral("cuadro_40"));
        cuadro_40->setGeometry(QRect(60, 150, 31, 31));
        cuadro_40->setAcceptDrops(false);
        cuadro_40->setAutoFillBackground(false);
        cuadro_40->setOverwriteMode(true);
        cuadro_40->setMaximumBlockCount(1);
        cuadro_41 = new QPlainTextEdit(centralWidget);
        cuadro_41->setObjectName(QStringLiteral("cuadro_41"));
        cuadro_41->setGeometry(QRect(90, 150, 31, 31));
        cuadro_41->setAcceptDrops(false);
        cuadro_41->setAutoFillBackground(false);
        cuadro_41->setOverwriteMode(true);
        cuadro_41->setMaximumBlockCount(1);
        cuadro_42 = new QPlainTextEdit(centralWidget);
        cuadro_42->setObjectName(QStringLiteral("cuadro_42"));
        cuadro_42->setGeometry(QRect(240, 150, 31, 31));
        cuadro_42->setAcceptDrops(false);
        cuadro_42->setAutoFillBackground(false);
        cuadro_42->setOverwriteMode(true);
        cuadro_42->setMaximumBlockCount(1);
        cuadro_43 = new QPlainTextEdit(centralWidget);
        cuadro_43->setObjectName(QStringLiteral("cuadro_43"));
        cuadro_43->setGeometry(QRect(270, 150, 31, 31));
        cuadro_43->setAcceptDrops(false);
        cuadro_43->setAutoFillBackground(false);
        cuadro_43->setOverwriteMode(true);
        cuadro_43->setMaximumBlockCount(1);
        cuadro_44 = new QPlainTextEdit(centralWidget);
        cuadro_44->setObjectName(QStringLiteral("cuadro_44"));
        cuadro_44->setGeometry(QRect(30, 120, 31, 31));
        cuadro_44->setAcceptDrops(false);
        cuadro_44->setAutoFillBackground(false);
        cuadro_44->setOverwriteMode(true);
        cuadro_44->setMaximumBlockCount(1);
        cuadro_45 = new QPlainTextEdit(centralWidget);
        cuadro_45->setObjectName(QStringLiteral("cuadro_45"));
        cuadro_45->setGeometry(QRect(120, 180, 31, 31));
        cuadro_45->setAcceptDrops(false);
        cuadro_45->setAutoFillBackground(false);
        cuadro_45->setOverwriteMode(true);
        cuadro_45->setMaximumBlockCount(1);
        cuadro_46 = new QPlainTextEdit(centralWidget);
        cuadro_46->setObjectName(QStringLiteral("cuadro_46"));
        cuadro_46->setGeometry(QRect(240, 180, 31, 31));
        cuadro_46->setAcceptDrops(false);
        cuadro_46->setAutoFillBackground(false);
        cuadro_46->setOverwriteMode(true);
        cuadro_46->setMaximumBlockCount(1);
        cuadro_47 = new QPlainTextEdit(centralWidget);
        cuadro_47->setObjectName(QStringLiteral("cuadro_47"));
        cuadro_47->setGeometry(QRect(240, 120, 31, 31));
        cuadro_47->setAcceptDrops(false);
        cuadro_47->setAutoFillBackground(false);
        cuadro_47->setOverwriteMode(true);
        cuadro_47->setMaximumBlockCount(1);
        cuadro_48 = new QPlainTextEdit(centralWidget);
        cuadro_48->setObjectName(QStringLiteral("cuadro_48"));
        cuadro_48->setGeometry(QRect(150, 150, 31, 31));
        cuadro_48->setAcceptDrops(false);
        cuadro_48->setAutoFillBackground(false);
        cuadro_48->setOverwriteMode(true);
        cuadro_48->setMaximumBlockCount(1);
        cuadro_49 = new QPlainTextEdit(centralWidget);
        cuadro_49->setObjectName(QStringLiteral("cuadro_49"));
        cuadro_49->setGeometry(QRect(120, 120, 31, 31));
        cuadro_49->setAcceptDrops(false);
        cuadro_49->setAutoFillBackground(false);
        cuadro_49->setOverwriteMode(true);
        cuadro_49->setMaximumBlockCount(1);
        cuadro_50 = new QPlainTextEdit(centralWidget);
        cuadro_50->setObjectName(QStringLiteral("cuadro_50"));
        cuadro_50->setGeometry(QRect(90, 120, 31, 31));
        cuadro_50->setAcceptDrops(false);
        cuadro_50->setAutoFillBackground(false);
        cuadro_50->setOverwriteMode(true);
        cuadro_50->setMaximumBlockCount(1);
        cuadro_51 = new QPlainTextEdit(centralWidget);
        cuadro_51->setObjectName(QStringLiteral("cuadro_51"));
        cuadro_51->setGeometry(QRect(210, 180, 31, 31));
        cuadro_51->setAcceptDrops(false);
        cuadro_51->setAutoFillBackground(false);
        cuadro_51->setOverwriteMode(true);
        cuadro_51->setMaximumBlockCount(1);
        cuadro_52 = new QPlainTextEdit(centralWidget);
        cuadro_52->setObjectName(QStringLiteral("cuadro_52"));
        cuadro_52->setGeometry(QRect(180, 120, 31, 31));
        cuadro_52->setAcceptDrops(false);
        cuadro_52->setAutoFillBackground(false);
        cuadro_52->setOverwriteMode(true);
        cuadro_52->setMaximumBlockCount(1);
        cuadro_53 = new QPlainTextEdit(centralWidget);
        cuadro_53->setObjectName(QStringLiteral("cuadro_53"));
        cuadro_53->setGeometry(QRect(270, 120, 31, 31));
        cuadro_53->setAcceptDrops(false);
        cuadro_53->setAutoFillBackground(false);
        cuadro_53->setOverwriteMode(true);
        cuadro_53->setMaximumBlockCount(1);
        cuadro_54 = new QPlainTextEdit(centralWidget);
        cuadro_54->setObjectName(QStringLiteral("cuadro_54"));
        cuadro_54->setGeometry(QRect(60, 120, 31, 31));
        cuadro_54->setAcceptDrops(false);
        cuadro_54->setAutoFillBackground(false);
        cuadro_54->setOverwriteMode(true);
        cuadro_54->setMaximumBlockCount(1);
        cuadro_55 = new QPlainTextEdit(centralWidget);
        cuadro_55->setObjectName(QStringLiteral("cuadro_55"));
        cuadro_55->setGeometry(QRect(210, 240, 31, 31));
        cuadro_55->setAcceptDrops(false);
        cuadro_55->setAutoFillBackground(false);
        cuadro_55->setOverwriteMode(true);
        cuadro_55->setMaximumBlockCount(1);
        cuadro_56 = new QPlainTextEdit(centralWidget);
        cuadro_56->setObjectName(QStringLiteral("cuadro_56"));
        cuadro_56->setGeometry(QRect(90, 270, 31, 31));
        cuadro_56->setAcceptDrops(false);
        cuadro_56->setAutoFillBackground(false);
        cuadro_56->setOverwriteMode(true);
        cuadro_56->setMaximumBlockCount(1);
        cuadro_57 = new QPlainTextEdit(centralWidget);
        cuadro_57->setObjectName(QStringLiteral("cuadro_57"));
        cuadro_57->setGeometry(QRect(270, 270, 31, 31));
        cuadro_57->setAcceptDrops(false);
        cuadro_57->setAutoFillBackground(false);
        cuadro_57->setOverwriteMode(true);
        cuadro_57->setMaximumBlockCount(1);
        cuadro_58 = new QPlainTextEdit(centralWidget);
        cuadro_58->setObjectName(QStringLiteral("cuadro_58"));
        cuadro_58->setGeometry(QRect(150, 270, 31, 31));
        cuadro_58->setAcceptDrops(false);
        cuadro_58->setAutoFillBackground(false);
        cuadro_58->setOverwriteMode(true);
        cuadro_58->setMaximumBlockCount(1);
        cuadro_59 = new QPlainTextEdit(centralWidget);
        cuadro_59->setObjectName(QStringLiteral("cuadro_59"));
        cuadro_59->setGeometry(QRect(60, 270, 31, 31));
        cuadro_59->setAcceptDrops(false);
        cuadro_59->setAutoFillBackground(false);
        cuadro_59->setOverwriteMode(true);
        cuadro_59->setMaximumBlockCount(1);
        cuadro_60 = new QPlainTextEdit(centralWidget);
        cuadro_60->setObjectName(QStringLiteral("cuadro_60"));
        cuadro_60->setGeometry(QRect(180, 270, 31, 31));
        cuadro_60->setAcceptDrops(false);
        cuadro_60->setAutoFillBackground(false);
        cuadro_60->setOverwriteMode(true);
        cuadro_60->setMaximumBlockCount(1);
        cuadro_61 = new QPlainTextEdit(centralWidget);
        cuadro_61->setObjectName(QStringLiteral("cuadro_61"));
        cuadro_61->setGeometry(QRect(120, 240, 31, 31));
        cuadro_61->setAcceptDrops(false);
        cuadro_61->setAutoFillBackground(false);
        cuadro_61->setOverwriteMode(true);
        cuadro_61->setMaximumBlockCount(1);
        cuadro_62 = new QPlainTextEdit(centralWidget);
        cuadro_62->setObjectName(QStringLiteral("cuadro_62"));
        cuadro_62->setGeometry(QRect(210, 210, 31, 31));
        cuadro_62->setAcceptDrops(false);
        cuadro_62->setAutoFillBackground(false);
        cuadro_62->setOverwriteMode(true);
        cuadro_62->setMaximumBlockCount(1);
        cuadro_63 = new QPlainTextEdit(centralWidget);
        cuadro_63->setObjectName(QStringLiteral("cuadro_63"));
        cuadro_63->setGeometry(QRect(30, 270, 31, 31));
        cuadro_63->setAcceptDrops(false);
        cuadro_63->setAutoFillBackground(false);
        cuadro_63->setOverwriteMode(true);
        cuadro_63->setMaximumBlockCount(1);
        cuadro_64 = new QPlainTextEdit(centralWidget);
        cuadro_64->setObjectName(QStringLiteral("cuadro_64"));
        cuadro_64->setGeometry(QRect(150, 210, 31, 31));
        cuadro_64->setAcceptDrops(false);
        cuadro_64->setAutoFillBackground(false);
        cuadro_64->setOverwriteMode(true);
        cuadro_64->setMaximumBlockCount(1);
        cuadro_65 = new QPlainTextEdit(centralWidget);
        cuadro_65->setObjectName(QStringLiteral("cuadro_65"));
        cuadro_65->setGeometry(QRect(180, 240, 31, 31));
        cuadro_65->setAcceptDrops(false);
        cuadro_65->setAutoFillBackground(false);
        cuadro_65->setOverwriteMode(true);
        cuadro_65->setMaximumBlockCount(1);
        cuadro_66 = new QPlainTextEdit(centralWidget);
        cuadro_66->setObjectName(QStringLiteral("cuadro_66"));
        cuadro_66->setGeometry(QRect(30, 240, 31, 31));
        cuadro_66->setAcceptDrops(false);
        cuadro_66->setAutoFillBackground(false);
        cuadro_66->setOverwriteMode(true);
        cuadro_66->setMaximumBlockCount(1);
        cuadro_67 = new QPlainTextEdit(centralWidget);
        cuadro_67->setObjectName(QStringLiteral("cuadro_67"));
        cuadro_67->setGeometry(QRect(60, 240, 31, 31));
        cuadro_67->setAcceptDrops(false);
        cuadro_67->setAutoFillBackground(false);
        cuadro_67->setOverwriteMode(true);
        cuadro_67->setMaximumBlockCount(1);
        cuadro_68 = new QPlainTextEdit(centralWidget);
        cuadro_68->setObjectName(QStringLiteral("cuadro_68"));
        cuadro_68->setGeometry(QRect(90, 240, 31, 31));
        cuadro_68->setAcceptDrops(false);
        cuadro_68->setAutoFillBackground(false);
        cuadro_68->setOverwriteMode(true);
        cuadro_68->setMaximumBlockCount(1);
        cuadro_69 = new QPlainTextEdit(centralWidget);
        cuadro_69->setObjectName(QStringLiteral("cuadro_69"));
        cuadro_69->setGeometry(QRect(240, 240, 31, 31));
        cuadro_69->setAcceptDrops(false);
        cuadro_69->setAutoFillBackground(false);
        cuadro_69->setOverwriteMode(true);
        cuadro_69->setMaximumBlockCount(1);
        cuadro_70 = new QPlainTextEdit(centralWidget);
        cuadro_70->setObjectName(QStringLiteral("cuadro_70"));
        cuadro_70->setGeometry(QRect(270, 240, 31, 31));
        cuadro_70->setAcceptDrops(false);
        cuadro_70->setAutoFillBackground(false);
        cuadro_70->setOverwriteMode(true);
        cuadro_70->setMaximumBlockCount(1);
        cuadro_71 = new QPlainTextEdit(centralWidget);
        cuadro_71->setObjectName(QStringLiteral("cuadro_71"));
        cuadro_71->setGeometry(QRect(30, 210, 31, 31));
        cuadro_71->setAcceptDrops(false);
        cuadro_71->setAutoFillBackground(false);
        cuadro_71->setOverwriteMode(true);
        cuadro_71->setMaximumBlockCount(1);
        cuadro_72 = new QPlainTextEdit(centralWidget);
        cuadro_72->setObjectName(QStringLiteral("cuadro_72"));
        cuadro_72->setGeometry(QRect(120, 270, 31, 31));
        cuadro_72->setAcceptDrops(false);
        cuadro_72->setAutoFillBackground(false);
        cuadro_72->setOverwriteMode(true);
        cuadro_72->setMaximumBlockCount(1);
        cuadro_73 = new QPlainTextEdit(centralWidget);
        cuadro_73->setObjectName(QStringLiteral("cuadro_73"));
        cuadro_73->setGeometry(QRect(240, 270, 31, 31));
        cuadro_73->setAcceptDrops(false);
        cuadro_73->setAutoFillBackground(false);
        cuadro_73->setOverwriteMode(true);
        cuadro_73->setMaximumBlockCount(1);
        cuadro_74 = new QPlainTextEdit(centralWidget);
        cuadro_74->setObjectName(QStringLiteral("cuadro_74"));
        cuadro_74->setGeometry(QRect(240, 210, 31, 31));
        cuadro_74->setAcceptDrops(false);
        cuadro_74->setAutoFillBackground(false);
        cuadro_74->setOverwriteMode(true);
        cuadro_74->setMaximumBlockCount(1);
        cuadro_75 = new QPlainTextEdit(centralWidget);
        cuadro_75->setObjectName(QStringLiteral("cuadro_75"));
        cuadro_75->setGeometry(QRect(150, 240, 31, 31));
        cuadro_75->setAcceptDrops(false);
        cuadro_75->setAutoFillBackground(false);
        cuadro_75->setOverwriteMode(true);
        cuadro_75->setMaximumBlockCount(1);
        cuadro_76 = new QPlainTextEdit(centralWidget);
        cuadro_76->setObjectName(QStringLiteral("cuadro_76"));
        cuadro_76->setGeometry(QRect(120, 210, 31, 31));
        cuadro_76->setAcceptDrops(false);
        cuadro_76->setAutoFillBackground(false);
        cuadro_76->setOverwriteMode(true);
        cuadro_76->setMaximumBlockCount(1);
        cuadro_77 = new QPlainTextEdit(centralWidget);
        cuadro_77->setObjectName(QStringLiteral("cuadro_77"));
        cuadro_77->setGeometry(QRect(90, 210, 31, 31));
        cuadro_77->setAcceptDrops(false);
        cuadro_77->setAutoFillBackground(false);
        cuadro_77->setOverwriteMode(true);
        cuadro_77->setMaximumBlockCount(1);
        cuadro_78 = new QPlainTextEdit(centralWidget);
        cuadro_78->setObjectName(QStringLiteral("cuadro_78"));
        cuadro_78->setGeometry(QRect(210, 270, 31, 31));
        cuadro_78->setAcceptDrops(false);
        cuadro_78->setAutoFillBackground(false);
        cuadro_78->setOverwriteMode(true);
        cuadro_78->setMaximumBlockCount(1);
        cuadro_79 = new QPlainTextEdit(centralWidget);
        cuadro_79->setObjectName(QStringLiteral("cuadro_79"));
        cuadro_79->setGeometry(QRect(180, 210, 31, 31));
        cuadro_79->setAcceptDrops(false);
        cuadro_79->setAutoFillBackground(false);
        cuadro_79->setOverwriteMode(true);
        cuadro_79->setMaximumBlockCount(1);
        cuadro_80 = new QPlainTextEdit(centralWidget);
        cuadro_80->setObjectName(QStringLiteral("cuadro_80"));
        cuadro_80->setGeometry(QRect(270, 210, 31, 31));
        cuadro_80->setAcceptDrops(false);
        cuadro_80->setAutoFillBackground(false);
        cuadro_80->setOverwriteMode(true);
        cuadro_80->setMaximumBlockCount(1);
        cuadro_81 = new QPlainTextEdit(centralWidget);
        cuadro_81->setObjectName(QStringLiteral("cuadro_81"));
        cuadro_81->setGeometry(QRect(60, 210, 31, 31));
        cuadro_81->setAcceptDrops(false);
        cuadro_81->setAutoFillBackground(false);
        cuadro_81->setOverwriteMode(true);
        cuadro_81->setMaximumBlockCount(1);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 400, 21));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        label->setText(QApplication::translate("MainWindow", "SUDOKU  ", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
